name: Deploy site to live
on:
  push:
    branches: 
    - stable(LIVE)
  pull_request:
    branches:
    - stable(LIVE)
  # manual trigger
  workflow_dispatch:
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 FTP Deploy
      # You may pin to the exact commit or the version.
      # uses: SamKirkland/FTP-Deploy-Action@8a24039354ee91000cb948cb4a1dbdf1a1b94a3c
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        # ftp server
        server: ${{ secrets.FTP_SERVER }}
        # ftp username
        username: siskostaa
        # ftp password
        password: ${{ secrets.FTP_PASSWORD }}
        # Server port to connect to (read your web hosts docs)
        port: 21
        # An array of glob patterns, these files will not be included in the publish/delete process
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.editorconfig
          **/.env.example
          **/README.md
