name: Deploy site to live
on:
  push:
    branches: [ main ]
  # manual trigger
  workflow_dispatch:
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: FTP Interact
      uses: priradev/ftp-interactions@v0.2.9-beta
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: sikostaa
        password: ${{ secrets.FTP_PASSWORD }}
        ftpAction: Copy
        # optional
        port: 21
        ignoreCertificateErrors: false
